<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-18T13:23:00 IST" name="Suite" finished-at="2022-07-18T13:23:32 IST" duration-ms="31487">
    <groups>
    </groups>
    <test started-at="2022-07-18T13:23:00 IST" name="Test_Chrome" finished-at="2022-07-18T13:23:17 IST" duration-ms="16099">
      <class name="Com.Test.VerifyLogin_Test">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:Com.Test.VerifyLogin_Test@5ddeb7cb]" started-at="2022-07-18T13:23:00 IST" name="setUp" finished-at="2022-07-18T13:23:06 IST" duration-ms="5124" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Verify_TC_01_LoginWithValidCredentials()[pri:0, instance:Com.Test.VerifyLogin_Test@5ddeb7cb]" started-at="2022-07-18T13:23:06 IST" name="Verify_TC_01_LoginWithValidCredentials" finished-at="2022-07-18T13:23:16 IST" duration-ms="10142" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Com.Test.VerifyLogin_Test.Verify_TC_01_LoginWithValidCredentials(VerifyLogin_Test.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_TC_01_LoginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Com.Test.VerifyLogin_Test@5ddeb7cb]" started-at="2022-07-18T13:23:16 IST" name="tearDown" finished-at="2022-07-18T13:23:17 IST" duration-ms="108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Com.Test.VerifyLogin_Test -->
    </test> <!-- Test_Chrome -->
    <test started-at="2022-07-18T13:23:17 IST" name="Test_Edge" finished-at="2022-07-18T13:23:32 IST" duration-ms="15119">
      <class name="Com.Test.VerifyLogin_Test">
        <test-method is-config="true" signature="inisializationsetup()[pri:0, instance:Com.Test.VerifyLogin_Test@7a5ceedd]" started-at="2022-07-18T13:23:00 IST" name="inisializationsetup" finished-at="2022-07-18T13:23:00 IST" duration-ms="434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inisializationsetup -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:Com.Test.VerifyLogin_Test@7a5ceedd]" started-at="2022-07-18T13:23:17 IST" name="setUp" finished-at="2022-07-18T13:23:20 IST" duration-ms="3136" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Verify_TC_01_LoginWithValidCredentials()[pri:0, instance:Com.Test.VerifyLogin_Test@7a5ceedd]" started-at="2022-07-18T13:23:20 IST" name="Verify_TC_01_LoginWithValidCredentials" finished-at="2022-07-18T13:23:30 IST" duration-ms="10099" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Com.Test.VerifyLogin_Test.Verify_TC_01_LoginWithValidCredentials(VerifyLogin_Test.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_TC_01_LoginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Com.Test.VerifyLogin_Test@7a5ceedd]" started-at="2022-07-18T13:23:32 IST" name="tearDown" finished-at="2022-07-18T13:23:32 IST" duration-ms="205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Com.Test.VerifyLogin_Test -->
    </test> <!-- Test_Edge -->
  </suite> <!-- Suite -->
</testng-results>
